baseURL = "https://gr33ngiant112.github.io/"
languageCode = "en-us"
title = "A blog?"
theme = "m10c"
paginate = 5

[params]
  author = "Austin Harris"
  description = "A place for my thoughts, tech stuff, and cooking"
  [[params.social]]
    name = "github"
    url = "https://github.com/gr33ngiant112"


 # Green theme
# [params.style]
#   darkestColor = "#d35050"
#   darkColor = "#212121"
#   lightColor = "#f5e3e0"
#   lightestColor = "#f5f5f5"
#   primaryColor = "#fff"

# # Dark theme
#   [params.style]
#    darkestColor = "#463625"
#    darkColor = "#2a3738"
#    primaryColor = "#eeee6a"
#    lightColor = "#96a879"
#    lightestColor = "#ffffff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"